baseurl: https://khstats.com/
title: KH STATS
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: 'UA-136820093-1'
params:
  copyright: '&copy;2022 Katherine Hoffman'
  description: Blog posts about statistics, programming, and the role of the biostatistician.
  email: kathoffman.stats@gmail.com
  navlinks:
    - home: yes
      name: Home
      url: blog/
    - name: About
      url: about/
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - Contributions towards more meaningful and reproducible medical research.
  social:
    email: kathoffman.stats@gmail.com
    github: https://github.com/kathoffman
    googleplus: https://scholar.google.com/citations?user=73RvTUoAAAAJ&hl=en
    linkedin: https://www.linkedin.com/in/katherinelhoffman
    twitter: https://twitter.com/kat_hoffman_
  style: default
