---
title: "An Illustrated Guide to TMLE, Part II: The Algorithm"
author: "Katherine Hoffman"
date: 2020-12-11T01:13:14-05:00
draft: false
image: /img/tmle/tmle_crop.jpeg
weight: 5
categories: ["statistics","R"]
math: true
tags: ["statistics","causal inference","R","lmtp","TMLE","Targeted Maximum Likelihood Estimation","introduction to TMLE","targeted learning"]
output:
  blogdown::html_page:
    toc: false
    toc_depth: 1
---



<p>The second post of a three-part series to help beginners and/or visual learners understand Targeted Maximum Likelihood Estimation (TMLE). This section walks through the <strong>TMLE algorithm for the mean difference in outcomes for a binary treatment and binary outcome</strong>.</p>
<!--more-->
<p><strong><em>December 6, 2020.</em></strong></p>
<html>
<link rel="stylesheet" href="/style.css" />
</html>
<p>The second post of a three-part series to help beginners and/or visual learners understand Targeted Maximum Likelihood Estimation (TMLE). This section walks through the <strong>TMLE algorithm for the mean difference in outcomes for a binary treatment and binary outcome</strong>. <br> <br> This post is an expansion of a printable “visual guide” available on my <a href="https://github.com/kathoffman/causal-inference-visual-guides">Github</a>. I hope it helps analysts who feel out-of-practice reading mathematical notation follow along with the TMLE algorithm. A web-based key without explanations is also available <a href="https://khstats.com/blog/tmle/visual-key">here</a>.</p>
<html>
<head>
<title>
HTML Image as link
</title>
</head>
<body>
<a href="https://github.com/kathoffman/CI-visual-guides/blob/master/visual-guides/TMLE.pdf">
<img alt="cheatsheet" src="/img/tmle/tmle.jpg"
         width=100%">
</a>
</body>
</html>
<hr />
<p>⬅️<a href="https://khstats.com/blog/tmle/tutorial/"><em>Return to Part I: Motivation</em></a></p>
<div id="part-ii-the-algorithm" class="section level1">
<h1>Part II: The Algorithm:</h1>
<p><a href="#why-the-visual-guide">Why the Visual Guide? 🎨</a></p>
<p><a href="#tmle-step-by-step">TMLE, Step-by-Step 🚶🏽️</a></p>
<ol style="list-style-type: decimal">
<li><p><a href="#step-1-estimate-the-outcome">Estimate the Outcome</a></p></li>
<li><p><a href="#step-2-estimate-the-probability-of-treatment">Estimate the Probability of Treatment</a></p></li>
<li><p><a href="#step-3-estimate-the-fluctuation-parameter">Estimate the Fluctuation Parameter</a></p></li>
<li><p><a href="#step-4-update-the-initial-estimates-of-the-expected-outcome">Update the Initial Estimates of the Expected Outcome</a></p></li>
<li><p><a href="#step-5-compute-the-statistical-estimand-of-interest">Compute the Statistical Estimand of Interest</a></p></li>
<li><p><a href="#step-6-calculate-the-standard-errors-for-confidence-intervals-and-p-values">Calculate the Standard Errors for Confidence Intervals and P-values</a></p></li>
</ol>
<p><a href="#using-the-tmle-package">Using the <code>tmle</code> package 📦</a></p>
<p><a href="#full-tutorial-code">Full tutorial code 💻</a></p>
<p>➡️<a href="https://khstats.com/blog/tmle/tutorial-pt3/"><em>Skip to Part III: Evaluation</em></a></p>
<hr />
</div>
<div id="why-the-visual-guide" class="section level1">
<h1>Why the Visual Guide? 🎨</h1>
<p>TMLE was developed in 2007 by Mark van der Laan and colleagues at UC Berkeley, and it is slowly but surely starting to see more widespread use. Since learning about TMLE, I’ve believed many more analysts with a skill set similar to mine <em>could</em> be using TMLE, but perhaps find even the most introductory resources to be a bit daunting.</p>
<p>I am a very applied thinker, and I’ve tried to write this tutorial in the way I would have found most useful and accessible when I began learning about TMLE. Each step is accompanied by:</p>
<ol style="list-style-type: decimal">
<li>a non-rigorous explanation</li>
<li>an equation using the simplest notation possible</li>
<li>in-line <code>R</code> code</li>
<li>a small graphic representing the computation on a data frame or vector</li>
</ol>
<p>This last piece is super important for me, because I remember best when I associate an image with what I’ve learned. If the graphics are also useful to you, it may be helpful to open this <a href="https://khstats.com/blog/tmle/visual-key">corresponding key</a> in another browser or print the <a href="https://github.com/kathoffman/causal-inference-visual-guides">visual guide</a> for reference.</p>
<p>This tutorial is not meant to replace the resources I used to learn TMLE, but rather to supplement them. I use the same mathematical notation as the TMLE literature to make it easier to move back and forth. I hope you find the way I think about the algorithm useful, but if not, consider checking out the references I’ve listed in <a href="https://khstats.com/blog/tmle/tutorial-pt3/#resources-to-learn-more"><em>Part III</em></a>. TMLE is a very powerful method and will undoubtedly only grow in popularity in statistics and data science.</p>
</div>
<div id="tmle-step-by-step" class="section level1">
<h1>TMLE, Step-by-Step 🚶🏽</h1>
<p>Let’s look at the algorithm step-by-step. As you’re reading, keep in mind that there are <code>R</code> packages that will do this for you as easily as running a <code>glm()</code> or <code>coxph()</code> function. This tutorial is to help understand what’s going on behind-the-scenes.</p>
<p>One final note before we dive into the algorithm:</p>
<div id="superlearning" class="section level3">
<h3>Superlearning</h3>
<p>I use the ensemble learning method superlearning (also known as “stacking”) to demonstrate TMLE. This is because superlearning is theoretically and empirically proven to yield the best results in TMLE.</p>
<p>If you’re new to superlearning/stacking, the necessary knowledge for this post is that it allows you to combine many machine learning algorithms for prediction. When I use <code>SuperLearner()</code> in the following example code, I could have used <code>glm()</code>, <code>randomForest()</code>, or any other parametric or non-parametric supervised learning algorithm.</p>
<html>
<head>
<title>
HTML Image as link
</title>
</head>
<body>
<a href="https://khstats.com/blog/sl/superlearning">
<img alt="cheatsheet" src="/img/Superlearning.jpg"  
         width="50%" style="float:right; padding-left:60px;">
</a>
</body>
</html>
<p>Note that the choice of base learners for superlearning is not the point of this post. In practice we simply want to add flexible machine learning models which we think <strong>may</strong> reflect the underlying data distribution. For a tutorial on superlearning, you can check out one of my <a href="https://khstats.com/blog/sl/superlearning">previous blog posts</a>.</p>
</div>
<div id="initial-set-up" class="section level3">
<h3>Initial set up</h3>
<p>Let’s first load the necessary libraries and set a seed.</p>
<pre class="r"><code>library(tidyverse) # for data manipulation
library(gt) # for table printing
library(SuperLearner) # for ensemble learning

set.seed(7) # for reproducible results</code></pre>
<p>Next, let’s simulate a data set for demonstration of the algorithm. This data will have a very simple structure: a binary treatment, <span class="math inline">\(A\)</span>; binary outcome, <span class="math inline">\(Y\)</span>; and four confounders: <span class="math inline">\(W_1\)</span>, <span class="math inline">\(W_2\)</span>, <span class="math inline">\(W_3\)</span>, and <span class="math inline">\(W_4\)</span>.</p>
<p><img src="/img/tmle/1_data_structure.png" style="width:80.0%" /></p>
<pre class="r"><code>generate_data &lt;- function(n){ 
    W1 &lt;- rbinom(n, size=1, prob=0.2) # binary confounder
    W2 &lt;- rbinom(n, size=1, prob=0.5) # binary confounder
    W3 &lt;- round(runif(n, min=2, max=7)) # continuous confounder
    W4 &lt;- round(runif(n, min=0, max=4)) # continuous confounder
    A  &lt;- rbinom(n, size=1, prob= plogis(-0.2 + 0.2*W2 + log(0.1*W3) + 0.3*W4 + 0.2*W1*W4)) # binary treatment depends on confounders
    Y &lt;- rbinom(n, size=1, prob= plogis(-1 + A - 0.1*W1 + 0.2*W2 + 0.3*W3 - 0.1*W4 + sin(0.1*W2*W4))) # binary outcome depends on confounders
    return(tibble(Y, W1, W2, W3, W4, A))
}

n &lt;- 1000
dat_obs &lt;- generate_data(n) # generate a data set with n observations

dat_obs %&gt;%
  head() %&gt;%
  gt() %&gt;%
  tab_header(&quot;Simulated data set.&quot;)</code></pre>
<div id="fkgwpykulw" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#fkgwpykulw .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#fkgwpykulw .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fkgwpykulw .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#fkgwpykulw .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#fkgwpykulw .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fkgwpykulw .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fkgwpykulw .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#fkgwpykulw .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#fkgwpykulw .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#fkgwpykulw .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#fkgwpykulw .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#fkgwpykulw .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#fkgwpykulw .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#fkgwpykulw .gt_from_md > :first-child {
  margin-top: 0;
}

#fkgwpykulw .gt_from_md > :last-child {
  margin-bottom: 0;
}

#fkgwpykulw .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#fkgwpykulw .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#fkgwpykulw .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#fkgwpykulw .gt_row_group_first td {
  border-top-width: 2px;
}

#fkgwpykulw .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fkgwpykulw .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#fkgwpykulw .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#fkgwpykulw .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fkgwpykulw .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fkgwpykulw .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#fkgwpykulw .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#fkgwpykulw .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fkgwpykulw .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fkgwpykulw .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fkgwpykulw .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fkgwpykulw .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fkgwpykulw .gt_left {
  text-align: left;
}

#fkgwpykulw .gt_center {
  text-align: center;
}

#fkgwpykulw .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#fkgwpykulw .gt_font_normal {
  font-weight: normal;
}

#fkgwpykulw .gt_font_bold {
  font-weight: bold;
}

#fkgwpykulw .gt_font_italic {
  font-style: italic;
}

#fkgwpykulw .gt_super {
  font-size: 65%;
}

#fkgwpykulw .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#fkgwpykulw .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#fkgwpykulw .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#fkgwpykulw .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#fkgwpykulw .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#fkgwpykulw .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="6" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>Simulated data set.</th>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Y</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">W1</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">W2</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">W3</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">W4</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">A</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">6</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td></tr>
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">6</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">0</td></tr>
    <tr><td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">0</td></tr>
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">5</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td></tr>
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">5</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">0</td></tr>
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">6</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td></tr>
  </tbody>
  
  
</table>
</div>
<p>As mentioned earlier, TMLE can estimate many different statistical estimands of interest. In this example, our statistical estimand is the mean difference in outcomes between those who received the treatment and those who did not, adjusting for confounders.</p>
<p>Under causal assumptions, this could be <em>identifiable</em> as the Average Treatment Effect (ATE). I won’t go through the identification process here (see <a href="https://khstats.com/blog/tmle/tutorial-pt3/#resources-to-learn-more"><em>Part III, References</em></a>), but since TMLE is often used for causal inference, let’s pretend for this example that we previously met causal assumptions and call our statistical estimand, <span class="math inline">\(\Psi\)</span>, the ATE.</p>
<p><span class="math display">\[ATE = \Psi = E_W[\mathrm{E}[Y|A=1,\mathbf{W}] - \mathrm{E}[Y|A=0,\mathbf{W}]]\]</span>
The ATE, once we estimate it, will be interpretable as the mean difference in outcomes in a hypothetical world where everyone received the treatment compared to a hypothetical world where no one received the treatment.</p>
<p>At this point in set-up, we should also pick our base machine learning algorithms to combine via superlearning to estimate the expected outcome and probability of treatment. Let’s use LASSO (<code>glmnet</code>), random forests (<code>ranger</code>), Multivariate Adaptive Regression Splines (MARS) (<code>earth</code>), and a generalized linear model (<code>glm</code>) for demonstration.</p>
<pre class="r"><code>sl_libs &lt;- c(&#39;SL.glmnet&#39;, &#39;SL.ranger&#39;, &#39;SL.earth&#39;, &#39;SL.glm&#39;) # a library of machine learning algorithms (penalized regression, random forests, and multivariate adaptive regression splines)</code></pre>
</div>
<div id="step-1-estimate-the-outcome" class="section level2">
<h2>Step 1: Estimate the Outcome</h2>
<p>The very first step of TMLE is to <strong>estimate the expected value of the outcome</strong> using treatment and confounders as predictors.</p>
<p>This is what that looks like in mathematical notation. There is some function <span class="math inline">\(Q\)</span> which takes <span class="math inline">\(A\)</span> and <span class="math inline">\(\mathbf{W}\)</span> as inputs and yields the conditional expectation of <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[Q(A,\mathbf{W}) = \mathrm{E}[Y|A,\mathbf{W}]\]</span>
We can use any regression to estimate this conditional expectation, but it is best to use flexible machine learning models so that we don’t have unnecessary assumptions on the underlying distribution of the data.</p>
<p>We can think about the above equation as some generic regression function in <code>R</code> called <code>fit()</code> with inputs in formula form: <code>outcome ~ predictors</code>:</p>
<p><img src="/img/tmle/2_outcome_fit.png" style="width:70.0%" />
In real <code>R</code> code, we’ll use the <code>SuperLearner()</code> function to fit a weighted combination of multiple machine learning models (defined earlier in <code>sl_libs</code>). This function takes the outcome <code>Y</code> as a vector and a data frame <code>X</code> as predictors.</p>
<pre class="r"><code>Y &lt;- dat_obs$Y
W_A &lt;- dat_obs %&gt;% select(-Y) # remove the outcome to make a matrix of predictors (A, W1, W2, W3, W4) for SuperLearner
Q &lt;- SuperLearner(Y = Y, # Y is the outcome vector
                  X = W_A, # W_A is the matrix of W1, W2, W3, W4, and A
                  family=binomial(), # specify we have a binary outcome
                  SL.library = sl_libs) # specify our superlearner library of LASSO, RF, and MARS</code></pre>
<p>Then, we should estimate the outcome for every observation under three different scenarios:</p>
<p><strong>1. If every observation received the treatment they <em>actually</em> received.</strong></p>
<p>We can get this expected outcome estimate by simply calling <code>predict()</code> on the model fit without specifying any new data.</p>
<p><span class="math display">\[\hat{Q}(A,\mathbf{W}) = \mathrm{\hat{E}}[Y|A,\mathbf{W}]\]</span></p>
<p>We will save that vector of estimates as a new object in <code>R</code>.</p>
<p><img src="/img/tmle/3_QA.png" style="width:50.0%" /></p>
<pre class="r"><code>Q_A &lt;- as.vector(predict(Q)$pred) # obtain predictions for everyone using the treatment they actually received</code></pre>
<p><strong>2. If every observation received the treatment.</strong></p>
<p>To do this, we’ll first need to create a data set where every observation received the treatment of interest, whether they actually did or not. Then we can call the <code>predict()</code> function on that data set.</p>
<p><span class="math display">\[\hat{Q}(1,\mathbf{W}) = \mathrm{\hat{E}}[Y|A=1,\mathbf{W}]\]</span></p>
<p><img src="/img/tmle/4_Q1.png" style="width:80.0%" /></p>
<pre class="r"><code>W_A1 &lt;- W_A %&gt;% mutate(A = 1)  # data set where everyone received treatment
Q_1 &lt;- as.vector(predict(Q, newdata = W_A1)$pred) # predict on that everyone-exposed data set</code></pre>
<p><strong>3. If every observation received the control.</strong></p>
<p>Similarly, we create a data set where every observation did <em>not</em> receive the treatment of interest, whether they actually did or not, and call the <code>predict()</code> function again.</p>
<p><span class="math display">\[\hat{Q}(0,\mathbf{W}) = \mathrm{\hat{E}}[Y|A=0,\mathbf{W}]\]</span></p>
<p><img src="/img/tmle/5_Q1.png" style="width:80.0%" /></p>
<pre class="r"><code>W_A0 &lt;- W_A %&gt;% mutate(A = 0) # data set where no one received treatment
Q_0 &lt;- as.vector(predict(Q, newdata = W_A0)$pred)</code></pre>
<p><strong><em>Next</em></strong>, let’s create a new data frame, <code>dat_tmle</code>, to hold the three vectors we’ve created so far, along with the treatment status <span class="math inline">\(A\)</span> and observed outcome <span class="math inline">\(Y\)</span>. Notice that when <span class="math inline">\(A=1\)</span>, the expected outcome <span class="math inline">\(\mathrm{\hat{E}}[Y|A,\mathbf{W}]\)</span> equals the expected outcome under treatment <span class="math inline">\(\mathrm{\hat{E}}[Y|A=1,\mathbf{W}]\)</span>. When <span class="math inline">\(A=0\)</span>, the expected outcome <span class="math inline">\(\mathrm{\hat{E}}[Y|A,\mathbf{W}]\)</span> equals the expected outcome under no treatment <span class="math inline">\(\mathrm{\hat{E}}[Y|A=0,\mathbf{W}]\)</span>.</p>
<pre class="r"><code>dat_tmle &lt;- tibble(Y = dat_obs$Y, A = dat_obs$A, Q_A, Q_0, Q_1)
dat_tmle %&gt;%
  head() %&gt;%
  gt() %&gt;%
  tab_header(&quot;TMLE Algorithm after Step 1&quot;)</code></pre>
<div id="wqrrijfakd" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#wqrrijfakd .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wqrrijfakd .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wqrrijfakd .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wqrrijfakd .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wqrrijfakd .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wqrrijfakd .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wqrrijfakd .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wqrrijfakd .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wqrrijfakd .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wqrrijfakd .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wqrrijfakd .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wqrrijfakd .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#wqrrijfakd .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wqrrijfakd .gt_from_md > :first-child {
  margin-top: 0;
}

#wqrrijfakd .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wqrrijfakd .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wqrrijfakd .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#wqrrijfakd .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#wqrrijfakd .gt_row_group_first td {
  border-top-width: 2px;
}

#wqrrijfakd .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wqrrijfakd .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#wqrrijfakd .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#wqrrijfakd .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wqrrijfakd .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wqrrijfakd .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wqrrijfakd .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wqrrijfakd .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wqrrijfakd .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wqrrijfakd .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wqrrijfakd .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wqrrijfakd .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wqrrijfakd .gt_left {
  text-align: left;
}

#wqrrijfakd .gt_center {
  text-align: center;
}

#wqrrijfakd .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wqrrijfakd .gt_font_normal {
  font-weight: normal;
}

#wqrrijfakd .gt_font_bold {
  font-weight: bold;
}

#wqrrijfakd .gt_font_italic {
  font-style: italic;
}

#wqrrijfakd .gt_super {
  font-size: 65%;
}

#wqrrijfakd .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#wqrrijfakd .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#wqrrijfakd .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#wqrrijfakd .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#wqrrijfakd .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#wqrrijfakd .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="5" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>TMLE Algorithm after Step 1</th>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Y</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">A</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Q_A</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Q_0</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Q_1</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">0.8461853</td>
<td class="gt_row gt_right">0.6770917</td>
<td class="gt_row gt_right">0.8461853</td></tr>
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">0.6986440</td>
<td class="gt_row gt_right">0.6986440</td>
<td class="gt_row gt_right">0.8589257</td></tr>
    <tr><td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">0.4932538</td>
<td class="gt_row gt_right">0.4932538</td>
<td class="gt_row gt_right">0.7188934</td></tr>
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">0.8213403</td>
<td class="gt_row gt_right">0.6363132</td>
<td class="gt_row gt_right">0.8213403</td></tr>
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">0</td>
<td class="gt_row gt_right">0.6266258</td>
<td class="gt_row gt_right">0.6266258</td>
<td class="gt_row gt_right">0.8151742</td></tr>
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">0.8578239</td>
<td class="gt_row gt_right">0.6966588</td>
<td class="gt_row gt_right">0.8578239</td></tr>
  </tbody>
  
  
</table>
</div>
<!-- *Also note that our expected outcomes are on the original outcome scale (i.e. probability, rather than the $logit$ probability).* -->
<p>We could stop here and get our estimate of the ATE by computing the average difference between <span class="math inline">\(\mathrm{\hat{E}}[Y|A=1,\mathbf{W}]\)</span> and <span class="math inline">\(\mathrm{\hat{E}}[Y|A=0,\mathbf{W}]\)</span>, which <em>would</em> be the mean difference in the expected outcomes, conditional on confounders. This estimation method is often called <strong>standardization</strong>, <strong>simple substitution estimation</strong>, <strong>g-formula estimation</strong>, or <strong>G-computation</strong>.</p>
<p><span class="math display">\[\hat{ATE}_{G-comp}= \hat{\Psi}_{G-comp} = \frac{1}{N}\sum_{i=1}^{N}(\mathrm{\hat{E}}[Y|A=1,\mathbf{W}]-\mathrm{\hat{E}}[Y|A=0,\mathbf{W}])\]</span>
<img src="/img/tmle/ate_gcomp.png" style="width:50.0%" /></p>
<pre class="r"><code>ate_gcomp &lt;- mean(dat_tmle$Q_1 - dat_tmle$Q_0)
ate_gcomp</code></pre>
<pre><code>## [1] 0.195287</code></pre>
<p>However, this G-computation ATE estimate does not have the appropriate bias-variance tradeoff for the ATE because it was built to have the best bias-variance tradeoff for estimating the <em>outcome</em>, conditional on confounders, rather than the ATE. We also cannot compute the standard error of the estimator because we don’t know the sampling distribution of the machine learning estimates.</p>
<p>⤴️<a href="#part-ii-the-algorithm"><em>Back to the top</em></a></p>
</div>
<div id="step-2-estimate-the-probability-of-treatment" class="section level2">
<h2>Step 2: Estimate the Probability of Treatment</h2>
<p>The next step is to estimate the probability of treatment, given confounders. This quantity is often called the <strong>propensity score</strong>, as in it gives the probability or <em>propensity</em> that an observation will receive a treatment of interest.</p>
<p><span class="math display">\[g(\mathbf{W}) = \mathrm{Pr}(A=1|\mathbf{W})\]</span>
<img src="/img/tmle/6_treatment_fit.png" style="width:60.0%" /></p>
<p>We will estimate <span class="math inline">\(\mathrm{Pr}(A=1|\mathbf{W})\)</span> in the same way as we estimated <span class="math inline">\(\mathrm{E}[Y|A,\mathbf{W}]\)</span>: using the superlearner algorithm.</p>
<pre class="r"><code>A &lt;- dat_obs$A
W &lt;- dat_obs %&gt;% select(-Y, -A) # matrix of predictors that only contains the confounders W1, W2, W3, and W4
g &lt;- SuperLearner(Y = A, # outcome is the A (treatment) vector
                  X = W, # W is a matrix of predictors
                  family=binomial(), # treatment is a binomial outcome
                  SL.library=sl_libs) # using same candidate learners; could use different learners</code></pre>
<p>Then we need to compute three different quantities from this model fit:</p>
<p><strong>1. The inverse probability of receiving treatment.</strong></p>
<p><span class="math display">\[H(1,\mathbf{W}) = \frac{1}{g(\mathbf{W})} = \frac{1}{\mathrm{Pr}(A=1|\mathbf{W})}\]</span>
We can estimate the probability of receiving treatment for every observation by using the <code>predict()</code> funcion without specifying any new data, and then take the inverse of that.</p>
<p><img src="/img/tmle/7_H1.png" style="width:60.0%" /></p>
<pre class="r"><code>g_w &lt;- as.vector(predict(g)$pred) # Pr(A=1|W)
H_1 &lt;- 1/g_w</code></pre>
<p><strong>2. The negative inverse probability of not receiving treatment.</strong></p>
<p><span class="math display">\[H(0,\mathbf{W}) = -\frac{1}{1-g(\mathbf{W})}= -\frac{1}{\mathrm{Pr}(A=0|\mathbf{W})}\]</span>
The probability of not receiving treatment for a binary treatment is simply 1 minus the probability of treatment.</p>
<p><img src="/img/tmle/8_H0.png" style="width:70.0%" /></p>
<pre class="r"><code>H_0 &lt;- -1/(1-g_w) # Pr(A=0|W) is 1-Pr(A=1|W)</code></pre>
<p><strong>3. If the observation was treated, the inverse probability of receiving treatment, and if they were not treated, the negative inverse probability of not receiving treatment.</strong> I’ll discuss why later, but in the TMLE literature this is called the <strong>clever covariate</strong>.</p>
<p><span class="math display">\[H(A,\mathbf{W}) = \frac{\mathrm{I}(A=1)}{\mathrm{Pr}(A=1|\mathbf{W})}-\frac{\mathrm{I}(A=0)}{\mathrm{Pr}(A=0|\mathbf{W})}\]</span></p>
<p><img src="/img/tmle/9_HA.png" style="width:50.0%" /></p>
<p>To calculate the clever covariate, we’ll first add the <span class="math inline">\(H(1,\mathbf{W})\)</span> and <span class="math inline">\(H(0,\mathbf{W})\)</span> vectors to our <code>dat_tmle</code> data frame, and then we can use <span class="math inline">\(A\)</span> to assign <span class="math inline">\(H(A,\mathbf{W})\)</span>.</p>
<pre class="r"><code>dat_tmle &lt;- # add clever covariate data to dat_tmle
  dat_tmle %&gt;%
  bind_cols(
         H_1 = H_1,
         H_0 = H_0) %&gt;%
  mutate(H_A = case_when(A == 1 ~ H_1, # if A is 1 (treated), assign H_1
                       A == 0 ~ H_0))  # if A is 0 (not treated), assign H_0</code></pre>
<p>We now have our initial estimates of the outcome, and the estimates of the probability of treatment:</p>
<pre class="r"><code>dat_tmle %&gt;% head() %&gt;% gt() %&gt;% tab_header(&quot;TMLE Algorithm after Step 2&quot;) %&gt;% fmt_number(everything(), decimals = 2)</code></pre>
<div id="hjkpoiqvpu" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#hjkpoiqvpu .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hjkpoiqvpu .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hjkpoiqvpu .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hjkpoiqvpu .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hjkpoiqvpu .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hjkpoiqvpu .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hjkpoiqvpu .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hjkpoiqvpu .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hjkpoiqvpu .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hjkpoiqvpu .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hjkpoiqvpu .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hjkpoiqvpu .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#hjkpoiqvpu .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hjkpoiqvpu .gt_from_md > :first-child {
  margin-top: 0;
}

#hjkpoiqvpu .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hjkpoiqvpu .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hjkpoiqvpu .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hjkpoiqvpu .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hjkpoiqvpu .gt_row_group_first td {
  border-top-width: 2px;
}

#hjkpoiqvpu .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hjkpoiqvpu .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hjkpoiqvpu .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hjkpoiqvpu .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hjkpoiqvpu .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hjkpoiqvpu .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hjkpoiqvpu .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hjkpoiqvpu .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hjkpoiqvpu .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hjkpoiqvpu .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hjkpoiqvpu .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hjkpoiqvpu .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hjkpoiqvpu .gt_left {
  text-align: left;
}

#hjkpoiqvpu .gt_center {
  text-align: center;
}

#hjkpoiqvpu .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hjkpoiqvpu .gt_font_normal {
  font-weight: normal;
}

#hjkpoiqvpu .gt_font_bold {
  font-weight: bold;
}

#hjkpoiqvpu .gt_font_italic {
  font-style: italic;
}

#hjkpoiqvpu .gt_super {
  font-size: 65%;
}

#hjkpoiqvpu .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#hjkpoiqvpu .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#hjkpoiqvpu .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hjkpoiqvpu .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#hjkpoiqvpu .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#hjkpoiqvpu .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="8" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>TMLE Algorithm after Step 2</th>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Y</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">A</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Q_A</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Q_0</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Q_1</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">H_1</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">H_0</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">H_A</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">1.00</td>
<td class="gt_row gt_right">1.00</td>
<td class="gt_row gt_right">0.85</td>
<td class="gt_row gt_right">0.68</td>
<td class="gt_row gt_right">0.85</td>
<td class="gt_row gt_right">2.18</td>
<td class="gt_row gt_right">&minus;1.85</td>
<td class="gt_row gt_right">2.18</td></tr>
    <tr><td class="gt_row gt_right">1.00</td>
<td class="gt_row gt_right">0.00</td>
<td class="gt_row gt_right">0.70</td>
<td class="gt_row gt_right">0.70</td>
<td class="gt_row gt_right">0.86</td>
<td class="gt_row gt_right">1.60</td>
<td class="gt_row gt_right">&minus;2.67</td>
<td class="gt_row gt_right">&minus;2.67</td></tr>
    <tr><td class="gt_row gt_right">0.00</td>
<td class="gt_row gt_right">0.00</td>
<td class="gt_row gt_right">0.49</td>
<td class="gt_row gt_right">0.49</td>
<td class="gt_row gt_right">0.72</td>
<td class="gt_row gt_right">3.39</td>
<td class="gt_row gt_right">&minus;1.42</td>
<td class="gt_row gt_right">&minus;1.42</td></tr>
    <tr><td class="gt_row gt_right">1.00</td>
<td class="gt_row gt_right">1.00</td>
<td class="gt_row gt_right">0.82</td>
<td class="gt_row gt_right">0.64</td>
<td class="gt_row gt_right">0.82</td>
<td class="gt_row gt_right">2.39</td>
<td class="gt_row gt_right">&minus;1.72</td>
<td class="gt_row gt_right">2.39</td></tr>
    <tr><td class="gt_row gt_right">1.00</td>
<td class="gt_row gt_right">0.00</td>
<td class="gt_row gt_right">0.63</td>
<td class="gt_row gt_right">0.63</td>
<td class="gt_row gt_right">0.82</td>
<td class="gt_row gt_right">2.31</td>
<td class="gt_row gt_right">&minus;1.76</td>
<td class="gt_row gt_right">&minus;1.76</td></tr>
    <tr><td class="gt_row gt_right">1.00</td>
<td class="gt_row gt_right">1.00</td>
<td class="gt_row gt_right">0.86</td>
<td class="gt_row gt_right">0.70</td>
<td class="gt_row gt_right">0.86</td>
<td class="gt_row gt_right">2.14</td>
<td class="gt_row gt_right">&minus;1.88</td>
<td class="gt_row gt_right">2.14</td></tr>
  </tbody>
  
  
</table>
</div>
<p>⤴️<a href="#part-ii-the-algorithm"><em>Back to the top</em></a></p>
</div>
<div id="step-3-estimate-the-fluctuation-parameter" class="section level2">
<h2>Step 3: Estimate the Fluctuation Parameter</h2>
<p>To reiterate, in <a href="#step-1-estimate-the-outcome">Step 1</a> we estimated the expected outcome, conditional on treatment and confounders. We know those machine learning fits have an optimal bias-variance trade-off for estimating the outcome (conditional on treatment and confounders), rather than the ATE. <strong>We will now use information about the treatment mechanism (from Step 2) to optimize the bias-variance trade-off for the ATE so we can obtain valid inference.</strong></p>
<html>
<head>
<title>
HTML Image as link
</title>
</head>
<body>
<a href="">
<img alt="cheatsheet" src="/img/bear_with_me.jpg"
               style="float:right; padding-left:65px;" width=50%">
</a>
</body>
</html>
<p>🚨 <strong><em>Warning:</em></strong> this step is easy to code, but difficult to understand unless you have a background in semiparametric theory. Let’s first look at <em>what</em> we’re doing, and then I’ll discuss at a very high-level why we’re doing that in a <a href="#why-does-tmle-work">later section</a>.</p>
<p>The point of this step is to solve an <em>estimating equation</em> for the <em>efficient influence function</em> (EIF) of our estimand of interest. Without diving into what an EIF or an estimating equation is, let’s accept for a moment that they will help us:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Update our initial outcome estimates</strong> so that our estimate of the ATE is asymptotically unbiased (under certain conditions, see <a href="https://khstats.com/blog/tmle/tutorial-pt3/#properties-of-tmle"><em>Part III, Statistical Properties</em></a>).</p></li>
<li><p><strong>Calculate the variance</strong>, and thus the standard error, confidence interval, and p-value for our estimate of the ATE for hypothesis testing.</p></li>
</ol>
<p>Next, let’s take a look at a model that will help us solve an EIF estimating equation and then update our estimates:</p>
<p><span class="math display">\[logit(\mathrm{E}[Y|A,\mathbf{W}]) = logit(\mathrm{\hat{E}}[Y|A,\mathbf{W}]) + \epsilon H(A,\mathbf{W})\]</span></p>
<p>To reiterate, I haven’t explained at all why this step works; we’re just focusing on implementing it for now.</p>
<p>If we look at the left side, we can see this equation contains the true outcome <span class="math inline">\(Y\)</span>, just <span class="math inline">\(logit\)</span> transformed. Luckily for us, there’s a well-known model that <span class="math inline">\(logit\)</span> transforms the left side of an equation: logistic regression. Our estimating equation looks <em>a lot</em> like a simple logistic regression, actually: <span class="math inline">\(logit(\mathrm{E}[Y|X]) = \beta_0 + \beta_1 X\)</span>.</p>
<p>Do you see how our equation also has a vector on the right-hand side, <span class="math inline">\(H(A,\mathbf{W})\)</span>, with a corresponding coefficient, <span class="math inline">\(\epsilon\)</span>? The only difference is that the “intercept” in our equation, <span class="math inline">\(logit(\mathrm{\hat{E}}[Y|A,\mathbf{W}])\)</span> is not a constant value like <span class="math inline">\(\beta_0\)</span>; it is a vector of values. We can see it as an <strong>offset</strong> or a <strong>fixed intercept</strong> in a logistic regression, rather than a constant-value intercept.</p>
<p>Therefore, to accomplish our goal of solving an estimating equation for the EIF we can leverage standard statistical software and fit a logistic regression with one covariate, <span class="math inline">\(H(A,\mathbf{W})\)</span>, and the initial outcome estimate, <span class="math inline">\(logit(\mathrm{\hat{E}}[Y|A,\mathbf{W}])\)</span>, as a fixed intercept. The outcome of the logistic regression is the observed outcome, <span class="math inline">\(Y\)</span>.</p>
<p>Two technical points for application: we use <code>qlogis</code> to transform the probabilities <span class="math inline">\(\mathrm{\hat{E}}[Y|A,\mathbf{W}]\)</span> to the <span class="math inline">\(logit\)</span> scale. Also, the <code>R</code> code for a fixed intercept is <code>-1 + offset(fixed_intercept)</code>.</p>
<p><img src="/img/tmle/10_logistic_regression.png" /></p>
<pre class="r"><code>glm_fit &lt;- glm(Y ~ -1 + offset(qlogis(Q_A)) + H_A, data=dat_tmle, family=binomial)</code></pre>
<p><em>Note that we are only using a logistic regression because it happens to have the correct form for solving the estimating equation for the EIF for the ATE estimand. It has nothing to do with having a binary outcome, and it isn’t putting any parametric restraints on our data.</em></p>
<p>Next we need to save the coefficient from that logistic regression, which we will call <span class="math inline">\(\hat{\epsilon}\)</span>:</p>
<p><img src="/img/tmle/11_epsilon.png" style="width:40.0%" /></p>
<pre class="r"><code>eps &lt;- coef(glm_fit)</code></pre>
<p>In the TMLE literature, <span class="math inline">\(\epsilon\)</span> is called the <strong>fluctuation parameter</strong>, because it provides information about how much to change, or fluctuate, our initial outcome estimates. Similarly, <span class="math inline">\(H(A,\mathbf{W})\)</span> is called the <strong>clever covariate</strong> because it “cleverly” helps us solve for the EIF and then update our estimates.</p>
<p>We will use both the fluctuation parameter and clever covariate in the next step to update our initial estimates of the expected outcome, conditional on confounders and treatment.</p>
<p>⤴️<a href="#part-ii-the-algorithm"><em>Back to the top</em></a></p>
</div>
<div id="step-4-update-the-initial-estimates-of-the-expected-outcome" class="section level2">
<h2>Step 4: Update the Initial Estimates of the Expected Outcome</h2>
<p>Almost done! Let’s recap:</p>
<ul>
<li><p>In <a href="#estimate-the-outcome">Step 1</a>, we obtained <strong>initial estimates</strong> of the expected outcome using machine learning (ML). These ML estimates are optimized to estimate <span class="math inline">\(E[Y|A,W]\)</span>, not the ATE.</p></li>
<li><p>We need to update those initial expected outcome estimates using <strong>information about the treatment mechanism</strong>, so we computed the expected probability of treatment, conditional on confounders, in <a href="#estimate-the-probability-of-treatment">Step 2</a>.</p></li>
<li><p>Then, in <a href="#estimate-the-fluctuation-parameter">Step 3</a>, we used quantities from Step 1 and Step 2 to <strong>solve an estimating equation for the EIF</strong>. We didn’t talk about <em>why</em> this works; we simply accepted for now that this is how we can target our estimand of interest (the ATE).</p></li>
<li><p>Now, we will <strong>update our initial outcome estimates</strong> from Step 1 using information from Step 2 and 3 to obtain the correct bias-variance tradeoff for the ATE.</p></li>
</ul>
<p>To update our expected outcome estimates, we first need to <strong>put the initial expected outcome estimates on the <span class="math inline">\(logit\)</span> scale</strong> using <code>qlogis()</code> because that’s the scale we used to solve our estimating equation for the EIF in Step 3. Then we can <strong>calculate how much we need to fluctuate our initial estimates</strong> using the product of the clever covariate and fluctuation parameter: <span class="math inline">\(H(A,\mathbf{W}) \times \hat{\epsilon}\)</span>. These are our outputs of Step 2 and 3, respectively. We will <strong>add that quantity to the initial outcome estimates to create updated outcome estimates</strong>. Finally, we can <strong>put the updated estimates back on the true outcome scale</strong> using <code>plogis()</code>.</p>
<p><em>Note we can use <span class="math inline">\(expit\)</span> to show the inverse of the <span class="math inline">\(logit\)</span> function, and we will denote updates to the outcome regressions as <span class="math inline">\(\hat{\mathrm{E}}^*\)</span> instead of <span class="math inline">\(\hat{\mathrm{E}}\)</span>.</em></p>
<p><strong>1. Update the expected outcomes of all observations, given the treatment they actually received and their baseline confounders.</strong></p>
<p><span class="math display">\[\hat{\mathrm{E}}^*[Y|A,\mathbf{W}] = expit(logit(\mathrm{\hat{E}}[Y|A,\mathbf{W}]) + \hat{\epsilon}H(A,\mathbf{W}))\]</span></p>
<p><img src="/img/tmle/update_qAW.png" style="width:70.0%" /></p>
<pre class="r"><code>H_A &lt;- dat_tmle$H_A # for cleaner code in Q_A_update
Q_A_update &lt;- plogis(qlogis(Q_A) + eps*H_A)</code></pre>
<p><strong>2. Update the expected outcomes, conditional on baseline confounders and everyone receiving the treatment.</strong></p>
<p><span class="math display">\[\hat{\mathrm{E}}^*[Y|A=1,\mathbf{W}] = expit(logit(\mathrm{\hat{E}}[Y|A=1,\mathbf{W}]) + \hat{\epsilon}H(1,A))\]</span>
<img src="/img/tmle/12_update_Q1.png" style="width:70.0%" /></p>
<pre class="r"><code>Q_1_update &lt;- plogis(qlogis(Q_1) + eps*H_1)</code></pre>
<p><strong>3. Update the expected outcomes, conditional on baseline confounders and no one receiving the treatment.</strong></p>
<p><span class="math display">\[\hat{\mathrm{E}}^*[Y|A=0,\mathbf{W}] = expit(logit(\mathrm{\hat{E}}[Y|A=0,\mathbf{W}]) + \hat{\epsilon}H(0,W))\]</span>
<img src="/img/tmle/13_update_Q0.png" style="width:70.0%" /></p>
<pre class="r"><code>Q_0_update &lt;- plogis(qlogis(Q_0) + eps*H_0)</code></pre>
<p>⤴️<a href="#part-ii-the-algorithm"><em>Back to the top</em></a></p>
</div>
<div id="step-5-compute-the-statistical-estimand-of-interest" class="section level2">
<h2>Step 5: Compute the Statistical Estimand of Interest</h2>
<p>We now have updated expected outcomes estimates, so we can <strong>compute the ATE as the mean difference in the updated outcome estimates under treatment and no treatment</strong>:</p>
<p><span class="math display">\[\hat{ATE}_{TMLE} = \hat{\Psi}_{TMLE} = \frac{1}{N}\sum_{i=1}^{N}[\hat{E^*}[Y|A=1,\mathbf{W}] - \hat{E^*}[Y|A=0,\mathbf{W}]]\]</span></p>
<p><img src="/img/tmle/14_compute_ATE.png" style="width:60.0%" /></p>
<pre class="r"><code>tmle_ate &lt;- mean(Q_1_update - Q_0_update)
tmle_ate</code></pre>
<pre><code>## [1] 0.1911676</code></pre>
<p>We can then say, “the average treatment effect was estimated to be 19.1%.”</p>
<p>If causal assumptions were not met, we would say, “the proportion of observations who experienced the outcome, after adjusting for baseline confounders, was estimated to be 19.1% higher for those who received treatment compared to those who did not.”</p>
<p>⤴️<a href="#part-ii-the-algorithm"><em>Back to the top</em></a></p>
</div>
<div id="step-6-calculate-the-standard-errors-for-confidence-intervals-and-p-values" class="section level2">
<h2>Step 6: Calculate the Standard Errors for Confidence Intervals and P-values</h2>
<p>This point estimate is great, but we usually need an <strong>estimate of variance</strong> so that we can compute confidence intervals, test statistics, p-values, etc. This is another step that contains quite a lot of theory, so I’ll give another birds-eye view for now. If you’re curious, you can read more about this in <a href="https://khstats.com/blog/tmle/tutorial-pt3"><em>Part III</em></a>.</p>
<p>To obtain the standard errors, we first need to compute the <strong>Influence Function</strong> (IF), which is the empirical version of what we used our estimating equation to figure out in <a href="#step-3-estimate-the-fluctuation-parameter">Step 3</a>. The IF tells us <strong>how much each observation influences the final estimate</strong>.</p>
<p>The equation for the IF looks like this:</p>
<p><span class="math display">\[\hat{IF} = (Y-\hat{E^*}[Y|A,\mathbf{W}])H(A,\mathbf{W}) + \hat{E^*}[Y|A=1,\mathbf{W}] - \hat{E^*}[Y|A=0,\mathbf{W}] - \hat{ATE}\]</span></p>
<pre class="r"><code>infl_fn &lt;- (Y - Q_A_update) * H_A + Q_1_update - Q_0_update - tmle_ate</code></pre>
<p>Once we have the IF, we can <strong>take the square-root of its variance divided by the number of observations</strong> to get the standard error of our estimate.</p>
<p><span class="math display">\[\hat{SE} = \sqrt{\frac{var(\hat{IF})}{N}} \]</span></p>
<p><img src="/img/tmle/15_ses.png" style="width:100.0%" /></p>
<pre class="r"><code>tmle_se &lt;- sqrt(var(infl_fn)/nrow(dat_obs))</code></pre>
<p>Once we have that standard error, we can easily get the 95% confidence interval and p-value of our estimate.</p>
<pre class="r"><code>conf_low &lt;- tmle_ate - 1.96*tmle_se
conf_high &lt;- tmle_ate + 1.96*tmle_se
pval &lt;- 2 * (1 - pnorm(abs(tmle_ate / tmle_se)))

tibble(tmle_ate, conf_low, conf_high) %&gt;% head() %&gt;% gt() %&gt;% tab_header(&quot;TMLE Estimate of the ATE&quot;) %&gt;% fmt_number(everything(), decimals = 3)</code></pre>
<div id="hrilomjnxp" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#hrilomjnxp .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hrilomjnxp .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hrilomjnxp .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hrilomjnxp .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hrilomjnxp .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hrilomjnxp .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hrilomjnxp .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hrilomjnxp .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hrilomjnxp .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hrilomjnxp .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hrilomjnxp .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hrilomjnxp .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#hrilomjnxp .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hrilomjnxp .gt_from_md > :first-child {
  margin-top: 0;
}

#hrilomjnxp .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hrilomjnxp .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hrilomjnxp .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hrilomjnxp .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hrilomjnxp .gt_row_group_first td {
  border-top-width: 2px;
}

#hrilomjnxp .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hrilomjnxp .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hrilomjnxp .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hrilomjnxp .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hrilomjnxp .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hrilomjnxp .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hrilomjnxp .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hrilomjnxp .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hrilomjnxp .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hrilomjnxp .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hrilomjnxp .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hrilomjnxp .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hrilomjnxp .gt_left {
  text-align: left;
}

#hrilomjnxp .gt_center {
  text-align: center;
}

#hrilomjnxp .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hrilomjnxp .gt_font_normal {
  font-weight: normal;
}

#hrilomjnxp .gt_font_bold {
  font-weight: bold;
}

#hrilomjnxp .gt_font_italic {
  font-style: italic;
}

#hrilomjnxp .gt_super {
  font-size: 65%;
}

#hrilomjnxp .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#hrilomjnxp .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#hrilomjnxp .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hrilomjnxp .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#hrilomjnxp .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#hrilomjnxp .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="3" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>TMLE Estimate of the ATE</th>
    </tr>
    
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">tmle_ate</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">conf_low</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">conf_high</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">0.191</td>
<td class="gt_row gt_right">0.133</td>
<td class="gt_row gt_right">0.249</td></tr>
  </tbody>
  
  
</table>
</div>
<p>Then we can successfully report our ATE as 0.191 (95% CI: 0.133, 0.249).</p>
<p><em>Note that a TMLE estimator is asymptotically normally distributed, so we could bootstrap the entire algorithm to get our standard errors instead.</em></p>
<p>⤴️<a href="#part-ii-the-algorithm"><em>Back to the top</em></a></p>
</div>
</div>
<div id="using-the-tmle-package" class="section level1">
<h1>Using the <code>tmle</code> package 📦</h1>
<p>Luckily there are <code>R</code> packages so that you don’t have to hand code TMLE yourself. <code>R</code> packages to implement the TMLE algorithm include <a href="https://www.jstatsoft.org/article/view/v051i13"><code>tmle</code></a>, <a href="https://tlverse.org/tlverse-handbook/tmle3.html"><code>tmle3</code></a>, <a href="https://www.jstatsoft.org/article/view/v081i01"><code>ltmle</code></a>, <a href="https://cran.r-project.org/web/packages/drtmle/vignettes/using_drtmle.html"><code>drtmle</code></a>, and <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/nt-williams/ddd44c48390b8d976fad71750e48d8bf/raw/45db700a02bf92e2a55790e60ed48266a97ca4e7/intro-lmtp.html"><code>lmtp</code></a>.</p>
<p>The code using the original <code>tmle</code> package’s <code>tmle()</code> function is:</p>
<pre class="r"><code>tmle_fit &lt;-
  tmle::tmle(Y = Y, # outcome vector
           A = A, # treatment vector
           W = W, # matrix of confounders W1, W2, W3, W4
           Q.SL.library = sl_libs, # superlearning libraries from earlier for outcome regression Q(A,W)
           g.SL.library = sl_libs) # superlearning libraries from earlier for treatment regression g(W)

tmle_fit</code></pre>
<pre><code>##  Additive Effect
##    Parameter Estimate:  0.19188
##    Estimated Variance:  0.00088096
##               p-value:  1.0142e-10
##     95% Conf Interval: (0.13371, 0.25006) 
## 
##  Additive Effect among the Treated
##    Parameter Estimate:  0.18992
##    Estimated Variance:  0.00091243
##               p-value:  3.2259e-10
##     95% Conf Interval: (0.13072, 0.24913) 
## 
##  Additive Effect among the Controls
##    Parameter Estimate:  0.19372
##    Estimated Variance:  0.00101
##               p-value:  1.0908e-09
##     95% Conf Interval: (0.13143, 0.25601)</code></pre>
<p>We can get the same result (variation due to randomness in the machine learning models) in just a few lines of code: the estimate using the original <code>tmle</code> package is 0.192 (95% CI: 0.134, 0.25).</p>
<hr />
<p>To learn more about the statistical properties of TMLE and the underlying theory, <a href="https://khstats.com/blog/tmle/tutorial-pt3"><em>continue on to Part III</em></a>. Alternatively, return to the motivation in <a href="https://khstats.com/blog/tmle/tutorial/"><em>Part I</em></a>, or see the full tutorial code below.</p>
<p>⤴️<a href="#part-ii-the-algorithm"><em>Back to the top</em></a></p>
<hr />
</div>
<div id="full-tutorial-code" class="section level1">
<h1>Full tutorial code</h1>
<pre class="r"><code>library(tidyverse) # for data manipulation
library(SuperLearner) # for ensemble learning

set.seed(7) # for reproducible results

sl_libs &lt;- c(&#39;SL.glmnet&#39;, &#39;SL.ranger&#39;, &#39;SL.earth&#39;) # a library of machine learning algorithms (penalized regression, random forests, and multivariate adaptive regression splines)

generate_data &lt;- function(n){ 
    W1 &lt;- rbinom(n, size=1, prob=0.2) # binary confounder
    W2 &lt;- rbinom(n, size=1, prob=0.5) # binary confounder
    W3 &lt;- round(runif(n, min=2, max=7)) # continuous confounder
    W4 &lt;- round(runif(n, min=0, max=4)) # continuous confounder
    A  &lt;- rbinom(n, size=1, prob= plogis(-0.2 + 0.2*W2 + log(0.1*W3) + 0.3*W4 + 0.2*W1*W4)) # binary treatment depends on confounders
    Y &lt;- rbinom(n, size=1, prob= plogis(-1 + A - 0.1*W1 + 0.2*W2 + 0.3*W3 - 0.1*W4 + sin(0.1*W2*W4))) # binary outcome depends on confounders
    return(tibble(Y, W1, W2, W3, W4, A))
}

n &lt;- 1000
dat_obs &lt;- generate_data(n) # generate a data set with n observations

Y &lt;- dat_obs$Y
W_A &lt;- dat_obs %&gt;% select(-Y) # remove the outcome to make a matrix of predictors (A, W1, W2, W3, W4) for SuperLearner

### Step 1: Estimate Q
Q &lt;- SuperLearner(Y = Y, # Y is the outcome vector
                  X = W_A, # W_A is the matrix of W1, W2, W3, W4, and A
                  family=binomial(), # specify we have a binary outcome
                  SL.library = sl_libs) # specify our superlearner library of LASSO, RF, and MARS
Q_A &lt;- as.vector(predict(Q)$pred) # obtain predictions for everyone using the treatment they actually received
W_A1 &lt;- W_A %&gt;% mutate(A = 1)  # data set where everyone received treatment
Q_1 &lt;- as.vector(predict(Q, newdata = W_A1)$pred) # predict on that everyone-exposed data set
W_A0 &lt;- W_A %&gt;% mutate(A = 0) # data set where no one received treatment
Q_0 &lt;- as.vector(predict(Q, newdata = W_A0)$pred)
dat_tmle &lt;- tibble(Y = dat_obs$Y, A = dat_obs$A, Q_A, Q_0, Q_1)

### Step 2: Estimate g and compute H(A,W)
A &lt;- dat_obs$A
W &lt;- dat_obs %&gt;% select(-Y, -A) # matrix of predictors that only contains the confounders W1, W2, W3, and W4
g &lt;- SuperLearner(Y = A, # outcome is the A (treatment) vector
                  X = W, # W is a matrix of predictors
                  family=binomial(), # treatment is a binomial outcome
                  SL.library=sl_libs) # using same candidate learners; could use different learners

g_w &lt;- as.vector(predict(g)$pred) # Pr(A=1|W)
H_1 &lt;- 1/g_w
H_0 &lt;- -1/(1-g_w) # Pr(A=0|W) is 1-Pr(A=1|W)
dat_tmle &lt;- # add clever covariate data to dat_tmle
  dat_tmle %&gt;%
  bind_cols(
         H_1 = H_1,
         H_0 = H_0) %&gt;%
  mutate(H_A = case_when(A == 1 ~ H_1, # if A is 1 (treated), assign H_1
                       A == 0 ~ H_0))  # if A is 0 (not treated), assign H_0

### Step 3: Estimate fluctuation parameter
glm_fit &lt;- glm(Y ~ -1 + offset(qlogis(Q_A)) + H_A, data=dat_tmle, family=binomial) # fixed intercept logistic regression
eps &lt;- coef(glm_fit) # save the only coefficient, called epsilon in TMLE lit

### Step 4: Update Q&#39;s
H_A &lt;- dat_tmle$H_A # for cleaner code in Q_A_update
Q_A_update &lt;- plogis(qlogis(Q_A) + eps*H_A) # updated expected outcome given treatment actually received
Q_1_update &lt;- plogis(qlogis(Q_1) + eps*H_1) # updated expected outcome for everyone receiving treatment
Q_0_update &lt;- plogis(qlogis(Q_0) + eps*H_0) # updated expected outcome for everyone not receiving treatment

### Step 5: Compute ATE
tmle_ate &lt;- mean(Q_1_update - Q_0_update) # mean diff in updated expected outcome estimates

### Step 6: compute standard error, CIs and pvals
infl_fn &lt;- (Y - Q_A_update) * H_A + Q_1_update - Q_0_update - tmle_ate # influence function
tmle_se &lt;- sqrt(var(infl_fn)/nrow(dat_obs)) # standard error
conf_low &lt;- tmle_ate - 1.96*tmle_se # 95% CI
conf_high &lt;- tmle_ate + 1.96*tmle_se
pval &lt;- 2 * (1 - pnorm(abs(tmle_ate / tmle_se))) # p-value at alpha .05

tmle_ate
conf_low
conf_high</code></pre>
<pre class="r"><code>sessionInfo()</code></pre>
<pre><code>## R version 4.1.3 (2022-03-10)
## Platform: x86_64-apple-darwin17.0 (64-bit)
## Running under: macOS Catalina 10.15.7
## 
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## attached base packages:
## [1] splines   stats     graphics  grDevices utils     datasets  methods  
## [8] base     
## 
## other attached packages:
##  [1] SuperLearner_2.0-28 gam_1.20.2          foreach_1.5.2      
##  [4] nnls_1.4            gt_0.6.0            forcats_0.5.1      
##  [7] stringr_1.4.0       dplyr_1.0.9         purrr_0.3.4        
## [10] readr_2.1.2         tidyr_1.2.0         tibble_3.1.6       
## [13] ggplot2_3.3.5       tidyverse_1.3.1    
## 
## loaded via a namespace (and not attached):
##  [1] httr_1.4.2         sass_0.4.1         jsonlite_1.8.0     modelr_0.1.8      
##  [5] bslib_0.3.1        Formula_1.2-4      assertthat_0.2.1   cellranger_1.1.0  
##  [9] yaml_2.3.5         pillar_1.7.0       backports_1.4.1    lattice_0.20-45   
## [13] glue_1.6.2         digest_0.6.29      checkmate_2.0.0    rvest_1.0.2       
## [17] colorspace_2.0-3   htmltools_0.5.2    Matrix_1.4-0       pkgconfig_2.0.3   
## [21] broom_0.8.0        earth_5.3.1        haven_2.5.0        bookdown_0.26     
## [25] scales_1.2.0       ranger_0.14.1      TeachingDemos_2.12 tzdb_0.3.0        
## [29] generics_0.1.3     ellipsis_0.3.2     withr_2.5.0        ROCR_1.0-11       
## [33] cli_3.3.0          survival_3.2-13    magrittr_2.0.3     crayon_1.5.1      
## [37] readxl_1.4.0       evaluate_0.15      fs_1.5.2           fansi_1.0.3       
## [41] xml2_1.3.3         cabinets_0.6.0     blogdown_1.9       tools_4.1.3       
## [45] hms_1.1.1          lifecycle_1.0.1    munsell_0.5.0      reprex_2.0.1      
## [49] glmnet_4.1-4       plotrix_3.8-2      compiler_4.1.3     jquerylib_0.1.4   
## [53] plotmo_3.6.2       rlang_1.0.2        grid_4.1.3         iterators_1.0.14  
## [57] rstudioapi_0.13    rmarkdown_2.13     gtable_0.3.0       codetools_0.2-18  
## [61] DBI_1.1.2          R6_2.5.1           lubridate_1.8.0    knitr_1.38        
## [65] fastmap_1.1.0      utf8_1.2.2         shape_1.4.6        tmle_1.5.0.2      
## [69] stringi_1.7.6      Rcpp_1.0.8.3       vctrs_0.4.1        dbplyr_2.1.1      
## [73] tidyselect_1.1.2   xfun_0.30</code></pre>
</div>
